pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/PKarunakar2205/CapstoneProject.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean test'
            }
        }

    }

    post {

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}