pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/PKarunakar2205/CapstoneProject.git'
            }
        }

        stage('Build') {
            steps {
                dir('Capstone_Project') {
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {

        always {
            archiveArtifacts artifacts: 'Capstone_Project/test-output/**/*', allowEmptyArchive: true
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}